// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6J_DDUQL5g_g1P8qlhm79fOYRh-SjPR0',
    appId: '1:1033479256721:web:93d5eeb0773826f7a15d30',
    messagingSenderId: '1033479256721',
    projectId: 'registration-e3220',
    authDomain: 'registration-e3220.firebaseapp.com',
    storageBucket: 'registration-e3220.appspot.com',
    measurementId: 'G-8WL7P8MERN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVaMyrFCKh1NwIxFAZ_1VU3HNi0KfOqTk',
    appId: '1:1033479256721:android:0edcebcee9dc1433a15d30',
    messagingSenderId: '1033479256721',
    projectId: 'registration-e3220',
    storageBucket: 'registration-e3220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgGyQjnoaAhz2IGsxyrHmiiz52rELggHA',
    appId: '1:1033479256721:ios:775293a536181af1a15d30',
    messagingSenderId: '1033479256721',
    projectId: 'registration-e3220',
    storageBucket: 'registration-e3220.appspot.com',
    iosBundleId: 'com.example.registrationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgGyQjnoaAhz2IGsxyrHmiiz52rELggHA',
    appId: '1:1033479256721:ios:7b7815d1c044fdaaa15d30',
    messagingSenderId: '1033479256721',
    projectId: 'registration-e3220',
    storageBucket: 'registration-e3220.appspot.com',
    iosBundleId: 'com.example.registrationFirebase.RunnerTests',
  );
}
